from pydantic import BaseModel, Field

class PromptResponse(BaseModel):
    """Schema for outgoing API responses."""
    generated_text: str = Field(
        ...,
        description="The markdown or text response generated by the model."
    )
    model_used: str = Field(
        ...,
        description="The model that processed the request."
    )